name: Check new version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # every month first day

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout ffmpeg
        uses: actions/checkout@v4
        with:
          repository: "FFmpeg/FFmpeg"
          path: 'ffmpeg'
          fetch-depth: 0

      - name: Get latest verion
        id: version
        run: |
          cd ./ffmpeg
          latest_tag=$(git tag | grep n | grep -v "-" | sort -r | head -n 1)
          echo "ffmpeg latest tag: $latest_tag"
          echo "LATEST_VERSION=$latest_tag" >> $GITHUB_ENV
          rm -rf ../ffmpeg

      - name: update to new version
        uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import re

            def parse_version(ver):
              if '-' in ver or ver == '':
                return 0
              return int(re.sub(r'[^0-9]+', r'', ver))

            file_path = './Sources/BuildScripts/XCFrameworkBuild/main.swift'
            with open(file_path, 'r', encoding='utf-8') as file:
              content = file.read()
            oldVersion = re.search(r'(case .FFmpeg[^"]+?)"(.+?)"', content).group(2)
            print("ffmpeg old version:", oldVersion)
            newVersion = '${{ env.LATEST_VERSION }}'
            print("ffmpeg new version:", newVersion)
            if parse_version(newVersion) > parse_version(oldVersion):
              content = re.sub(r'(case .FFmpeg[^"]+?)"(.+?)"', r'\1"${{ env.LATEST_VERSION }}"', content, count=1)
              set_env('FOUND_NEW_VERSION', '1')
              with open(file_path, 'w', encoding='utf-8') as file:
                file.write(content)
            

      - name: Create Pull Request
        if: env.FOUND_NEW_VERSION
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            ./Sources/BuildScripts/XCFrameworkBuild/main.swift
            ./README.md
          title: "bump version to ${{ env.LATEST_VERSION }}"
          body: "https://github.com/FFmpeg/FFmpeg/blob/${{ env.LATEST_VERSION }}/Changelog\n"
          commit-message: "chore: bump version to ${{ env.LATEST_VERSION }}"
          
